# -*- coding: utf-8 -*-
"""Estrutura de dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gWNZyjAVV9HJiskBIftbCky_-sG5smWo

**Primeiro a entrar é o primeiro a sair
FIFO**
"""

#Entendendo o conceito
fila = []

def enfileirar(elemento):
  fila.append(elemento)
  print(f"Elemento {elemento} foi enfileirado")

def desenfileirar():
  if len(fila) > 0 :
    primeiro_elemento = fila.pop(0)
    print(f"Elemento {primeiro_elemento} foi desenfileirado")
  else:
    print("A fila esta vazia")

enfileirar(3)
enfileirar(5)
enfileirar(9)
enfileirar(3)
enfileirar(5)
enfileirar(9)

print(fila)
print(len(fila))

desenfileirar()

print(fila)
print(len(fila))

desenfileirar()

print(fila)
print(len(fila))
desenfileirar()

print(fila)
print(len(fila))
desenfileirar()

print(fila)
print(len(fila))

"""**Pilha
LIFO
Ultimo a entrar é o primeiro a sair**
"""

pilha = []

def empilhar(elemento):
  pilha.append(elemento)
  print(f"Elemento {elemento} foi empilhado ")


def desempilhar():
  if len(pilha) > 0:
    topo = pilha.pop()
    print(f"Elemento {topo} foi desempilhado")
  else:
    print(f"A pilha esta vazia")

empilhar(3)
empilhar(5)
empilhar(9)
print(pilha)
print(len(pilha))

desempilhar()
print(pilha)
print(len(pilha))

desempilhar()
desempilhar()
print(pilha)
print(len(pilha))
desempilhar()

Lista_frutas = ["laranja", "maçã", "pera", "banana", "kiwi"]

primeira_fruta = Lista_frutas[0]
print(primeira_fruta)

ultima_fruta = Lista_frutas[-1]
print(ultima_fruta)

Lista_frutas.append("abacaxi")
print(Lista_frutas)

Lista_frutas.remove("maçã")
print(Lista_frutas)

if "banana" in Lista_frutas:
  print("Tem banana aqui dentro !!!! LA ELE ")

tamanho_da_lista = len(Lista_frutas)
print(tamanho_da_lista)

for fruta in Lista_frutas:
  print(f"Fruta: {fruta}")

frutas_em_maisculo = [f.upper() for f in Lista_frutas]
print(frutas_em_maisculo)

lista_de_bandas=[]

def enfileirar(elemento):
  lista_de_bandas.append(elemento)
  print(f"Elemento {elemento} foi enfileirado")

def desenfileirar():
  if len(lista_de_bandas) > 0 :
    primeiro_elemento = lista_de_bandas.pop(0)
    print(f"Elemento {primeiro_elemento} foi desenfileirado")
  else:
    print("A fila esta vazia")


def empilhar(elemento):
  lista_de_bandas.append(elemento)
  print(f"Elemento {elemento} foi empilhado ")


def desempilhar():
  if len(lista_de_bandas) > 0:
    topo = lista_de_bandas.pop()
    print(f"Elemento {topo} foi desempilhado")
  else:
    print(f"A pilha esta vazia")




enfileirar("Metallica")
enfileirar("Megadeth")
enfileirar("Thin Lizy")
enfileirar("Anthrax")
enfileirar("Slayer")
enfileirar("Black Label Society")
enfileirar("Ghost")
print(lista_de_bandas)

desenfileirar()
print(lista_de_bandas)
print(len(lista_de_bandas))


empilhar("Van Halen")
print(lista_de_bandas)
print(len(lista_de_bandas))

desempilhar()
print(lista_de_bandas)
print(len(lista_de_bandas))